routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
//Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('pacientes', 'PacienteController');
Route::get('search',array('as'=>'search','uses'=> 'PacienteController@search'));
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');
Route::prefix('triagems')->group(function(){
  Route::get('/create/{id}', 'TriagemController@create');
  Route::post('{id}', 'TriagemController@store');
  Route::get('/list/{id}', 'TriagemController@index');
  Route::get('{id}/edit', 'TriagemController@edit');
  Route::get('{id}/retriagem', 'TriagemController@retriagem');
  Route::patch('{id}', 'TriagemController@update');
  Route::get('/show/{id}', 'TriagemController@show');
});

Route::prefix('funcionario')->name('funcionario.')->group(function(){
  Route::get('/create', 'FuncionarioController@create')->name('create');
  Route::get('{id}/edit', 'FuncionarioController@edit')->name('edit');
  Route::get('/', 'FuncionarioController@index')->name('index');
  Route::post('/', 'FuncionarioController@store');
  Route::patch('{id}', 'FuncionarioController@update');
  Route::delete('{id}', 'FuncionarioController@destroy');
  Route::get('show/{id}', 'FuncionarioController@show');
});

Route::prefix('evolucoes')->group(function(){
  Route::get('/create/{evolucao}', 'EvolucaoController@create');
  Route::post('{evolucao}', 'EvolucaoController@store');
  Route::get('/list/{id}', 'EvolucaoController@index');
  Route::get('/show/{id}', 'EvolucaoController@show');
  Route::get('{id}/edit', 'EvolucaoController@edit');
  Route::delete('{id}', 'EvolucaoController@destroy');
  Route::patch('{id}', 'EvolucaoController@update');
});

Route::prefix('admin')->name('admin.')->namespace('Admin')->group(function () {
    Auth::routes();
    Route::middleware('auth:admin')->group(function () {
        Route::get('/', 'Auth\LoginController@showLoginForm');
        Route::resource('estabelecimentos', 'EstabelecimentoController');
        Route::resource('funcionarios', 'AdmEstabelecimentoController');
        Route::get('/home', 'HomeController@index')->name('home');
        Route::get('autocomplete',array('as'=>'autocomplete','uses'=> 'EstabelecimentoController@autocomplete'));
    });
});

resources/views/admin/layouts/base.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>GPSM</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" />
</head>
<body>
    <div id="system">
      <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom border-gray">
        <a class="navbar-brand" href="{{action('Admin\HomeController@index')}}">GPSM</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto">
            &nbsp;
          </ul>

          <ul class="nav navbar-nav navbar-right">

            <!-- Authentication Links -->
            @if (!Auth::guard('admin')->check())
              <!--<li><a href="{{ route('admin.login') }}" class="nav-link">Login</a></li>-->
              <li><a href="{{action('HomeController@index')}}" class="nav-link">Área de usuários</a></li>
            @else
              <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                  <span>Bem vindo, {{ Auth::guard('admin')->user()->name }}</span>

                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" role="menu">
                  <li><a href="{{action('Admin\EstabelecimentoController@index')}}" class="dropdown-item">Área Estabelecimentos</a></li>
                  <li><a href="{{action('Admin\AdmEstabelecimentoController@index')}}" class="dropdown-item">Área Funcionários</a></li>
                  <li>
                      <a class="dropdown-item" href="{{ route('admin.logout') }}"
                          onclick="event.preventDefault();
                              document.getElementById('logout-form').submit();">
                              Sair
                      </a>

                      <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
                          {{ csrf_field() }}
                      </form>
                    </li>
                  </ul>
                </li>
                @endif
              </ul>
            </div>
          </nav>
          @yield('content')
        </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.14/jquery.mask.js"></script>-->
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script type="text/javascript">
        $('#estabelecimento').autocomplete({
          source : "{{action('Admin\EstabelecimentoController@autocomplete')}}",
          minLength: 3,
          select: function(event, ui) {
              $('#estabelecimento').val(ui.value);
          }
        });
    </script>
</body>
</html>

resources/views/admin/layouts/basemasksearch.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>GPSM</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="system">
      <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom border-gray">
        <a class="navbar-brand" href="{{action('Admin\HomeController@index')}}">GPSM</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto">
            &nbsp;
          </ul>

          <ul class="nav navbar-nav navbar-right">

            <!-- Authentication Links -->
            @if (!Auth::guard('admin')->check())
              <!--<li><a href="{{ route('admin.login') }}" class="nav-link">Login</a></li>-->
              <li><a href="{{action('HomeController@index')}}" class="nav-link">Área de usuários</a></li>
            @else
              <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                  <span>Bem vindo, {{ Auth::guard('admin')->user()->name }}</span>

                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" role="menu">
                  <li><a href="{{action('Admin\EstabelecimentoController@index')}}" class="dropdown-item">Área Estabelecimentos</a></li>
                  <li><a href="{{action('Admin\AdmEstabelecimentoController@index')}}" class="dropdown-item">Área Funcionários</a></li>
                  <li>
                      <a class="dropdown-item" href="{{ route('admin.logout') }}"
                          onclick="event.preventDefault();
                              document.getElementById('logout-form').submit();">
                              Sair
                      </a>

                      <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
                          {{ csrf_field() }}
                      </form>
                    </li>
                  </ul>
                </li>
                @endif
              </ul>
            </div>
          </nav>
          @yield('content')
        </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.14/jquery.mask.js"></script>

</body>
</html>